name: 2025spring_cc
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.11
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - altair==5.5.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - jinja2==3.1.6
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - markupsafe==3.0.2
      - narwhals==1.42.0
      - numpy==2.3.0
      - packaging==24.2
      - pandas==2.3.0
      - pillow==11.2.1
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.4
      - rpds-py==0.25.1
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.45.1
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.1
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - watchdog==6.0.0
